### PR TITLE
Improve install documentation

### PR DESCRIPTION
**Pull request by NyakudyaA**
* Improving the documentation for this repo

### CODE REVIEW

**Comment by wlorenzetti** [comment]
Thanks @NyakudyaA , your improve is for docker deployment, original instructions was for classic django deploy.. Do you think is necessary specify it?

**Comment by NyakudyaA** [comment]
> Thanks @NyakudyaA , your improve is for docker deployment, original instructions was for classic django deploy.. Do you think is necessary specify it?

I can separate the two sections. One for docker and another for classic Django. Will that be ok. Do you also think we should install the front end by default in the docker? I can do another PR there

**Comment by wlorenzetti** [comment]
This sound good :) Thanks!

**Comment by wlorenzetti** [comment]
When you have time @NyakudyaA please make a PR with separated sections, Thanks!

**Comment by NyakudyaA** [comment]
I have already done so, I will push my changes when I am in front of a PC

**Comment by NyakudyaA** [comment]
@wlorenzetti I have pushed my changes

**Comment by wlorenzetti** [comment]
Thanks @NyakudyaA !

**Pull request merged**
